### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by FlerpyBird** [Ibot02/TMCRTracker#1]
I don't know if I'm just being stupid, but I'm pretty sure that there's no way to track keys. I was able to grab most of the items in Deepwood, and even beat the boss, yet the tracker thought I couldn't get anything past the second chest. Please add a way to track keys, it would make the tracker so much better.

**Comment by Ibot02** [comment]
There *is* a way to track keys, but it requires going to a dungeon's list of checks or the overview for all dungeons' keys.
What is broken is keysanity - it is supposed to show keys with the other items if that is enabled. For now, as a workaround, you can not turn on keysanity in the settings and track keys with each dungeon. I'll try to fix the keysanity thing asap.

**Comment by Ibot02** [comment]
And the keysanity version is now also fixed.
